### PR TITLE
fix: Generate correct topic links for speeches pages

### LINKED ISSUE #139: Icons missing in topics : https://main--xwalk-qantas--aemdemos.aem.page/speeches/qantas-airways-ltd-half-year-results-alan-joyce-qantas-ceo-speech

### PR DESCRIPTION
**Pull request by bharat941**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #139 

Test URLs:
- Before: https://www.qantasnewsroom.com.au/speeches/qantas-airways-ltd-half-year-results-alan-joyce-qantas-ceo-speech/
- After: https://issues-139--xwalk-qantas--aemdemos.aem.page/speeches/qantas-airways-ltd-half-year-results-alan-joyce-qantas-ceo-speech

### CODE REVIEW

File: blocks/side-navigation/side-navigation.js [hunk 1]
```diff
@@ -36,7 +36,7 @@ function getQueryIndexJsonEndpoint() {
 function getTopicLink(topic) {
   const currentUrl = window.location.href.toLowerCase();
   let topicLink = window.location.origin;
-  if (currentUrl.includes('/media-releases/')) {
+  if (currentUrl.includes('/media-releases/') || currentUrl.includes('/speeches/')) {
```
Comment (hmehta-adobe) [inline blocks/side-navigation/side-navigation.js:39]: Also add featured, qantas-responds

**Review by hmehta-adobe — APPROVED** [review]
